hipro/hiapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
app_name = 'hiapp'
urlpatterns = [
    path('',views.demo,name='demo'),
    path('login/',views.login,name='login'),
    path('home/', views.home, name='home'),
    path('AddItem/',views.additem,name='additem'),
    path('add_item',views.add_item,name='add_item'),
    path('delete_item/<int:itemid>/', views.delete_item, name='delete_item'),
    path('edit_item/<int:itemid>/', views.edit_item, name='edit_item'),
    path('update_item/<int:itemid>/', views.update_item, name='update_item'),
    path('get_mrp_item_id',views.get_mrp_item_id,name='get_mrp_item_id'),
 path('Additem/view-item-pricelist/', views.view_item_pricelist, name='view_item_pricelist'),
path('Additem/view-item-pricelist/generate-pdf/', views.generate_pdf, name='generate_pdf'),
    path('save_item_pricelist_bulk', views.save_item_pricelist_bulk, name='save_item_pricelist_bulk'),
    path('AddCategory/',views.addcategory,name='addcategory'),
    path('add_category',views.add_category,name='add_category'),
    path('delete_category/<int:categoryid>/',views.delete_category,name='delete_category'),
    path('edit_category/<int:categoryid>/',views.edit_category,name='edit_category'),
    path('update_category/<int:categoryid>/',views.update_category,name='update_category'),
    path('AddPricelist/', views.addpricelist, name='addpricelist'),
    path('add_pricelist', views.add_pricelist, name='add_pricelist'),
    path('delete_pricelist/<int:pricelistid>/', views.delete_pricelist, name='delete_pricelist'),
    path('edit_pricelist/<int:pricelistid>/', views.edit_pricelist, name='edit_pricelist'),
    path('update_pricelist/<int:pricelistid>/', views.update_pricelist, name='update_pricelist'),
    path('AddBBrand/', views.addbrand, name='addbrand'),
    path('add_brand', views.add_brand, name='add_brand'),
    path('delete_brand/<int:brandid>/', views.delete_brand, name='delete_brand'),
    path('edit_brand/<int:brandid>/', views.edit_brand, name='edit_brand'),
    path('update_brand/<int:brandid>/', views.update_brand, name='update_brand')
]

hipro/hipro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hiapp.urls')),
    path('party/',include('partyapp.urls')),
]

hipro/partyapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
app_name = 'partyapp'
urlpatterns = [
    path('', views.addparty, name='addparty'),
    path('add_party/', views.add_party, name='add_party'),
    path('SaleItem',views.saleitem,name='saleitem'),
    path('sale_item', views.sale_item, name='sale_item'),
    path('PurchaseItem', views.purchaseitem, name='purchaseitem'),
    path('purchase_item', views.purchase_item, name='purchase_item'),

]

hipro/templates/brand.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">

    <title>Hello, world!</title>
  </head>
  <body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'hiapp:additem' %}">Item Master</a>
          <a class="dropdown-item" href="#">Party Master</a>

          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'hiapp:home' %}">Back</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  </div>
<div class="container mt-3">
    {% for message in messages %}
        <p class="alert alert-success mt-3">{{ message }}</p>
    {% endfor %}
    <div class="row">
        <div class="col-sm-4">
            <h3 class="alert alert-info text-center">Brand Master</h3>
            {% if sel_brands %}
                <form action="{% url 'hiapp:update_brand' sel_brands.id %}" method="post">
                    {% csrf_token %}

                    <div>
                        <label for="brandname">Brand Name</label>
                        <input name="brandname" class="form-control" placeholder="Brand Name" value="{{ sel_brands.brandname }}" type="text">
                    </div>
                    <div>
                        <label for="branddescription">Brand Description</label>
                        <textarea name="branddescription" class="form-control" placeholder="Brand Description" type="text"> {{ sel_brands.branddescription }} </textarea>
                    </div><br>
                    <div>
                        <button type="submit" class="btn btn-success">Update Brand</button>
                    </div>
                </form>
            {% else %}
                <form action="{% url 'hiapp:add_brand' %}" method="post">
                    {% csrf_token %}

                            <div>
                                <label for="brandname">Brand Name</label>
                                <input name="brandname" class="form-control" placeholder="Brand Name" type="text">
                            </div>
                            <div>
                                <label for="branddescription">Brand Description</label>
                                <textarea name="branddescription" class="form-control" placeholder="Brand Description" type="text"></textarea>
                            </div><br>
                            <div>
                                <button type="submit" class="btn btn-success">Add Brand</button>
                            </div>

                </form>
            {% endif %}
        </div>
        <div class="col-sm-8">
            <h3 class="text-center alert alert-info">Show Brand Information</h3>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Brand Name</th>
                        <th scope="col">Brand Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for b in brands %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ b.brandname }}</td>
                            <td>{{ b.branddescription }}</td>
                            <td><a href="{% url 'hiapp:edit_brand' b.id %}" class="btn btn-warning btn-sm">Edit</a></td>
                            <td><a href="{% url 'hiapp:delete_brand' b.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div></div>
    </div>
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script crossorigin="anonymous" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

hipro/templates/category.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">

    <title>Hello, world!</title>
  </head>
  <body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'hiapp:additem' %}">Item Master</a>
          <a class="dropdown-item" href="#">Party Master</a>

          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'hiapp:home' %}">Back</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  </div>
<div class="container mt-3">
    {% for message in messages %}
        <p class="alert alert-success mt-3">{{ message }}</p>
    {% endfor %}
    <div class="row">
        <div class="col-sm-4">
            <h3 class="alert alert-info text-center">Category Master</h3>
            {% if sel_categories %}
                <form action="{% url 'hiapp:update_category' sel_categories.id %}" method="post">
                    {% csrf_token %}

                    <div>
                        <label for="categoryname">Category Name</label>
                        <input name="categoryname" class="form-control" placeholder="Category Name" value="{{ sel_categories.categoryname }}" type="text">
                    </div>
                    <div>
                        <label for="categorydescription">Category Description</label>
                        <textarea name="categorydescription" class="form-control" placeholder="Category Description" type="text">{{ sel_categories.categorydescription }}</textarea>
                    </div><br>
                    <div>
                        <button type="submit" class="btn btn-success">Update Category</button>
                    </div>
                </form>
            {% else %}
                <form action="{% url 'hiapp:add_category' %}" method="post">
                    {% csrf_token %}

                            <div>
                                <label for="categoryname">Category Name</label>
                                <input name="categoryname" class="form-control" placeholder="Category Name" type="text">
                            </div>
                            <div>
                                <label for="categorydescription">Category Description</label>
                                <textarea name="categorydescription" class="form-control" placeholder="Category Description" type="text"></textarea>
                            </div><br>
                            <div>
                                <button type="submit" class="btn btn-success">Add Category</button>
                            </div>

                </form>
            {% endif %}
        </div>
        <div class="col-sm-8">
            <h3 class="text-center alert alert-info">Show Category Information</h3>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Sl.No</th>
                        <th scope="col">Category Name</th>
                        <th scope="col">Category Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in categories %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ c.categoryname }}</td>
                            <td>{{ c.categorydescription }}</td>
                            <td><a href="{% url 'hiapp:edit_category' c.id %}" class="btn btn-warning btn-sm">Edit</a></td>
                            <td><a href="{% url 'hiapp:delete_category' c.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div></div>
    </div>
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script crossorigin="anonymous" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

hipro/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Billing</a>
  <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'hiapp:additem' %}">Item Master</a>
         <a class="dropdown-item" href= "{% url 'hiapp:addcategory' %}">Category Master</a>
          <a class="dropdown-item" href= "{% url 'hiapp:addbrand' %}">Brand Master</a>
            <a class="dropdown-item" href="{% url 'hiapp:addpricelist' %}">Pricelist Master</a>
          <a class="dropdown-item" href="{% url 'partyapp:addparty' %}">Party Master</a>

          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Transactions
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'partyapp:saleitem' %}">Sale</a>
         <a class="dropdown-item" href= "{% url 'partyapp:purchaseitem' %}">Purchase</a>

        </div>
      </li>

      <li class="nav-item">

          <li><a class="nav-link" href="{% url 'partyapp:saleitem' %}"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

hipro/templates/itempricelist.html
<!-- your_template.html -->
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Billing</a>
  <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'hiapp:additem' %}">Item Master</a>
         <a class="dropdown-item" href= "{% url 'hiapp:addcategory' %}">Category Master</a>
          <a class="dropdown-item" href= "{% url 'hiapp:addbrand' %}">Brand Master</a>
            <a class="dropdown-item" href="{% url 'hiapp:addpricelist' %}">Pricelist Master</a>
          <a class="dropdown-item" href="{% url 'partyapp:addparty' %}">Party Master</a>

          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Transactions
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'partyapp:saleitem' %}">Sale</a>
         <a class="dropdown-item" href= "{% url 'partyapp:purchaseitem' %}">Purchase</a>

        </div>
      </li>

      <li class="nav-item">

          <li><a class="nav-link" href="{% url 'partyapp:saleitem' %}"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hiapp:additem' %}">Back</a>
      </li>
    </ul>
  </div>
</nav>
  </div>
<h3 class="alert alert-warning text-center">Item Pricelist Information</h3>
<form action="" method="get">
                    {% csrf_token %}
    <table id="itemPricelistTable" class="table table-hover" >
        <thead>
            <tr>
                <th>Item Id</th>
                <th>PriceList</th>
                <th>MRP</th>
                <th>Discount</th>
                <th>Amount</th>
                <!-- Add more table headers as needed -->
            </tr>
        </thead>
        <tbody id="itemPricelistTableBody">
            {% for item in items %}
                <tr>
                     <td>{{ item.itemid1 }}</td>
                    <td>{{ item.itemid.itemname }}</td>

                    <td>{{ item.pricename }}</td>
                    <td>{{ item.mrp }}</td>
                    <td>{{ item.discount }}</td>
                    <td>{{ item.amount }}</td>
                    <!-- Add more table cells as needed -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
     <a href="{% url 'hiapp:generate-pdf' %}" class="btn btn-warning btn-sm">download</a>
</form>
    <!-- Include any necessary JavaScript here -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

hipro/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<style>
    body
    {text-align: center;}
    .login-container {
            margin: 0 auto; /* Center-align the container horizontally */
            width: 300px; /* Set the width of the container */
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #f9f9f9;
        }
</style>
 <div class="login-container">
        <h2>Login</h2>
<form action="login/" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name='username'placeholder="Enter the username"><br><br>
    <label for="password">Password</label>
    <input type="password" name='password' placeholder="Enter the password"><br><br>
    <input type="submit" value="Login">
</form>
      {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
 </div>
</body>
</html>

hipro/templates/sales_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Billing</a>
  <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item dropdown">
        <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
          Masters
        </a>
        <div aria-labelledby="navbarDropdown" class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'hiapp:additem' %}">Item Master</a>
         <a class="dropdown-item" href= "{% url 'hiapp:addcategory' %}">Category Master</a>
          <a class="dropdown-item" href= "{% url 'hiapp:addbrand' %}">Brand Master</a>
          <a class="dropdown-item" href="{% url 'partyapp:addparty' %}">Party Master</a>

          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'partyapp:purchaseitem' %}">Purchase</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  </div>
        <div class ="container mt-3">
    {% for message in messages %}
    <p class="alert alert-success mt-3">{{message}}</p>
    {% endfor %}
<div class="row">
        <div class="col-sm-4">
            <h3 class="alert alert-info text-center">Sales Report</h3>
            <!-- sales_list.html -->
<ul>
  {% for sale in sales %}
    <li>{{ sale.date }} - Sale No: {{ sale.sale_number }}</li>
    <ul>
      {% for item in sale.items.all %}
        <li>{{ item.item_name }}</li>
      {% endfor %}
    </ul>
  {% endfor %}
</ul>
        </div></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</body>
</html>